#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK

if __name__ == "__main__":
  import argparse
  import os
  from buckettools.vtktools import extract_subvtus

  parser = argparse.ArgumentParser( \
                      description="""Extract sub vtus visualization files""")
  parser.add_argument('filename', action='store', metavar='filename', type=str, nargs='+',
                      help='specify .xdmf, .pvd, .vtu or .pvtu filename(s)')
  parser.add_argument('-m', '--mesh', action='store', metavar='meshfilename', type=str, required=True,
                      help='specify a .xdmf mesh filename')
  parser.add_argument('-r', '--regionids', action='store', metavar='region_id', dest='regionids', type=int, nargs='+', required=True,
                      help='specify the region ids where the submesh is to be extracted')
  parser.add_argument('-o', '--output', action='store', metavar='outputfilename', type=str, default=True, const=None, required=False, nargs='?',
                      help='output filename or basename for vtu (and pvd where possible, defaults to filename_subvtu*.vtu and filename_subvtus.pvd)')

  args = parser.parse_args()

  extract_subvtus(args.filename, args.mesh, args.regionids, writefile=args.output)


