#!/usr/bin/env python

from optparse import OptionParser
import sys
import libspud
import buckettools.spud

# Let's start by parsing the options
optparser=OptionParser(usage='usage: %prog <options-file>',
                       add_help_option=True,
                       description="""This script takes a buckettools options file and writes """ +
                       """ufl, ufc and cpp header files based on the solver, functional and expression options.  """ +
                       """It also provides a cpp header file wrapping the namespaces of the ufc """ +
                       """corresponding to these ufl files.""" )

(options, argv) = optparser.parse_args()

if len(argv)<1:
    optparser.print_help()
    sys.exit(1)

# the options file name
options_filename  = argv[0]

# load the options tree
libspud.load_options(options_filename)

bucket = buckettools.spud.SpudBucket()
# populate the bucket based on the options file loaded above
bucket.fill()

# write out the ufl files described by the options tree
bucket.write_ufc()
# write a cpp header file to wrap the namespaces of the corresponding ufc
bucket.write_systemfunctionals_cpp()
bucket.write_systemsolvers_cpp()

# write out the cpp expression header files described by the options tree
bucket.write_cppexpressions()
# write a cpp header file to wrap the namespaces of the corresponding cpp
bucket.write_systemexpressions_cpp()

# write a cpp header file to wrap the namespaces of the visualization functionspace ufc
bucket.write_visualization_cpp()

# and we're done

