#!/usr/bin/env python

# Copyright (C) 2013 Columbia University in the City of New York and others.
#
# Please see the AUTHORS file in the main source directory for a full list
# of contributors.
#
# This file is part of TerraFERMA.
#
# TerraFERMA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# TerraFERMA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with TerraFERMA. If not, see <http://www.gnu.org/licenses/>.

# utility script for building TerraFERMA models

import os
import sys
import subprocess
import shutil
from optparse import OptionParser


def chdir(dirname):
  try:
    os.chdir(dirname)
  except OSError:
    print "ERROR no such directory "+dirname+"."
    sys.exit(1)

def getExtraCmakeOptions(options):
    """
    get extra -D options for cmake from the command line or the environment variable TF_CMAKE_EXTRA_DARGS
    """
    # get options from command line
    cmake_options = options.extra_Doptions

    #convert to string if None
    if (cmake_options == None):
        cmake_options = ''
        
    # get options from environment variable
    env_options = os.getenv('TF_CMAKE_EXTRA_DARGS')
    if (env_options == None):
        env_options = ''

    cmake_options += env_options
    return cmake_options.split()
        
if __name__ == "__main__":
    """
    Configure a build for a TerraFERMA project: defaults to out of tree build unless -d .
    """

    # set up the options parser
    usage = 'usage: %prog  filename.tfml [ -d build_directory ] -i [ -e executable_name]  [ -D "extra cmake args" ] [  "auxiliary files"]'
    parser = OptionParser(usage=usage)
    parser.add_option("-d","--build_dir",dest="build_dir",default="build", help="out of tree build directory")
    parser.add_option("-e","--executable_name",dest="executable", help="alternate name of executable, defaults to filename")
    parser.add_option("-D", dest="extra_Doptions",help="extra -D options for cmake")
    parser.add_option("-i", "--interactive", 
                      dest="interactive",action="store_true",default=False, 
                      help="use ccmake for interactive build <default is cmake>") 
    

    (options, args) = parser.parse_args()
    if len(args) == 0:
        print 'Error: must include filename.tfml'
        parser.print_help()
        sys.exit()
    else:
        tfmlfile = args[0]
        auxfiles = args[1:]

    # check for legal tfml filename
    if (not tfmlfile.endswith('.tfml')):
        print 'Error:  invalid filename.tfml'
        parser.print_help()
        sys.exit()

        
    build_dir = options.build_dir    
    interactive = options.interactive
    executable = options.executable

    # check if in tree or out of tree build
    if os.path.abspath(build_dir) == os.getcwd():
      out_of_tree_build = False
    else:
      out_of_tree_build = True
      optionsfile="../"+tfmlfile
    if (executable == None):
        executable = tfmlfile[:-5]

    # sort out any extra cmake options
    cmake_options = getExtraCmakeOptions(options)        

    print "***************************"
    print "Executable name =", executable
    print "Auxiliary files =", auxfiles
    print "Extra Cmake options =", cmake_options
    print "***************************"
    
    # make build_directory
    try:
        os.mkdir(build_dir)
    except OSError:
        pass

    # link auxiliary files in build_dir
    # FIXME: this needs to be sorted out to make sure names are consistent with tfml files (potentially use libspud to parse tfml?)
    # FIXME:  also should be careful about overwriting links particularly if build_dir = .
    for name in auxfiles:
        if (os.path.isfile(name)):
            subprocess.call(["ln","-sf",os.path.abspath(name),build_dir+"/"+os.path.basename(name)])
        else:
            print 'Error: auxiliary file', name,' not found'
            sys.exit(1)

    
    # set options file and build directory  
    if out_of_tree_build:
      chdir(build_dir)
      optionsfile = "../"+tfmlfile
    else:
      optionsfile = tfmlfile
      
    #run cmake or ccmake
    if interactive:
        cmake_prog = "ccmake"
    else:
        cmake_prog = "cmake"

    try:
        cmake_path = os.getenv('TF_CMAKE_PATH')
        subprocess.check_call([cmake_prog,cmake_path,"-DOPTIONSFILE="+optionsfile,"-DEXECUTABLE="+executable]+cmake_options)   
    except:
        print "ERROR while calling cmake in directory ", build_dir
        if out_of_tree_build:
          os.chdir("../")
    sys.exit(1)
    if out_of_tree_build:
      os.chdir("../")
    





