name: Build and Test

on: [push, pull_request]

jobs:

  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        name: [ "Build Focal" ]
        include:
        
          - name: "Build Focal"
            release: focal
    
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Get Name
        run: echo "name=$(echo ${GITHUB_REF//\//_} | cut -c 6-)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/${{ matrix.release }}/actions/Dockerfile
          push: true
          tags: terraferma/actions:${{ env.name }}-${{ matrix.release }}

  testing:

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: build
    if: always()

    strategy:
      fail-fast: false
      matrix:
        name: [ "Quick Tests Focal", "Short Tests Focal", "Medium Tests Focal" ]
        include:
        
          - name: "Quick Tests Focal"
            release: focal
            command: "OVERSUBSCRIBE=1 THREADS=2 make run_quicktests"

          - name: "Short Tests Focal"
            release: focal
            command: "OVERSUBSCRIBE=1 THREADS=2 make run_shorttests"

          - name: "Medium Tests Focal"
            release: focal
            command: "OVERSUBSCRIBE=1 THREADS=2 make run_mediumtests"

          - name: "Short Tutorial Tests Focal"
            release: focal
            command: "OVERSUBSCRIBE=1 THREADS=2 make run_shorttutorialtests"

    steps:

      - name: ${{ matrix.name }} Name
        run: echo "name=$(echo ${GITHUB_REF//\//_} | cut -c 6-)" >> $GITHUB_ENV

      - name: ${{ matrix.name }} Testing
        run: |
         chmod 777 .
         docker pull terraferma/actions:${{ env.name }}-${{ matrix.release }}
         docker run --workdir /home/tfuser/TerraFERMA/build terraferma/actions:${{ env.name }}-${{ matrix.release }} "${{ matrix.command }}"

