name: Build and Test

on: [push, pull_request]

jobs:

  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        name: [ "Build Focal" ]
        include:
        
          - name: "Build Focal"
            release: focal
    
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/${{ matrix.release }}/actions/Dockerfile
          push: true
          tags: terraferma/actions:${{ matrix.release }}-${{ github.sha }}

  testing:

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: build
    if: always()

    strategy:
      fail-fast: false
      matrix:
        name: [ "Short Focal" ]
        include:
        
          - name: "Short Focal"
            release: focal
            command: "THREADS=2 make run_shorttest"

    steps:

      - name: ${{ matrix.name }} Testing
        run: |
         chmod 777 .
         docker pull fluidity/actions:${{ matrix.release }}-${{ github.sha }}
         docker run --workdir /home/tfuser/TerraFERMA/build terraferma/actions:${{ matrix.release }}-${{ github.sha }} "${{ matrix.command }}"

  #    - uses: actions/upload-artifact@v2
  #      with:
  #        path: ${{ matrix.release }}-${{ matrix.output }}

  #    - name: ${{ matrix.name }} JUnit
  #      uses: mikepenz/action-junit-report@v2
  #      with:
  #        report_paths: ${{ matrix.release }}-${{ matrix.output }}
  #        github_token: ${{ secrets.GITHUB_TOKEN }}
  #        check_name: Test report ${{ matrix.name }}
  #        fail_on_failure: true
