name: Build and Test

on: [push, pull_request]

env:
  registry: ghcr.io

jobs:

  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        name: [ "Build Focal" ]
        include:
        
          - name: "Build Focal"
            release: focal
    
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v3

      - name: Get Name
        run: echo "name=$(echo ${GITHUB_REF//\//_} | cut -c 6-)" >> $GITHUB_ENV

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/${{ matrix.release }}/actions/Dockerfile
          push: true
          tags: ${{ env.registry }}/terraferma/actions:${{ env.name }}-${{ matrix.release }}

  testing:

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: build
    if: always()

    strategy:
      fail-fast: false
      matrix:
        name: [ "Quick Tests Focal", "Short Tests Focal", "Medium Tests Focal" ]
        include:
        
          - name: "Quick Tests Focal"
            release: focal
            command: "OVERSUBSCRIBE=1 THREADS=2 make run_quicktests"
            outputdir: "tests"
            outputtar: "quicktests.tar.gz"

          - name: "Short Tests Focal"
            release: focal
            command: "OVERSUBSCRIBE=1 THREADS=2 make run_shorttests"
            outputdir: "tests"
            outputtar: "shorttests.tar.gz"

          - name: "Medium Tests Focal"
            release: focal
            command: "OVERSUBSCRIBE=1 THREADS=2 make run_mediumtests"
            outputdir: "tests"
            outputtar: "mediumtests.tar.gz"

          - name: "Short Tutorial Tests Focal"
            release: focal
            command: "OVERSUBSCRIBE=1 THREADS=2 make run_shorttutorialtests"
            outputdir: "tutorials"
            outputtar: "shorttutorials.tar.gz"

          - name: "Medium Tutorial Tests Focal"
            release: focal
            command: "OVERSUBSCRIBE=1 THREADS=2 make run_mediumtutorialtests"
            outputdir: "tutorials"
            outputtar: "mediumtutorials.tar.gz"

          - name: "Build Cookbook Focal"
            release: focal
            command: "make build_cookbook"
            outputdir: "tutorials/manual"
            outputtar: "manual.tar.gz"

    steps:

      - name: ${{ matrix.name }} Name
        run: echo "name=$(echo ${GITHUB_REF//\//_} | cut -c 6-)" >> $GITHUB_ENV

      - name: ${{ matrix.name }} Testing
        run: |
         chmod 777 .
         docker pull ${{ env.registry }}/terraferma/actions:${{ env.name }}-${{ matrix.release }}
         docker run -v $PWD:/home/tfuser/shared -e HOST_UID=`id -u` -e HOST_GID=`id -g` --workdir /home/tfuser/TerraFERMA/build ${{ env.registry }}/terraferma/actions:${{ env.name }}-${{ matrix.release }} "${{ matrix.command }} || ( tar --exclude=*.build -cvzf ${{ matrix.outputtar }} ${{ matrix.outputdir }}; cp -v ${{ matrix.outputtar }} /home/tfuser/shared; ( exit 1 ) )"

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: ${{ matrix.outputtar }}
          name: failed_test_outputs



